package bean;

// Generated 9-lug-2014 12.20.42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * FattoriRischio generated by hbm2java
 */
public class FattoriRischio implements java.io.Serializable {

	private String nome;
	private Set rischiPazientes = new HashSet(0);

	public FattoriRischio() {
	}

	public FattoriRischio(String nome) {
		this.nome = nome;
	}

	public FattoriRischio(String nome, Set rischiPazientes) {
		this.nome = nome;
		this.rischiPazientes = rischiPazientes;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set getRischiPazientes() {
		return this.rischiPazientes;
	}

	public void setRischiPazientes(Set rischiPazientes) {
		this.rischiPazientes = rischiPazientes;
	}

}
