package bean;

// Generated 12-lug-2014 19.15.43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ConfermeId generated by hbm2java
 */
public class ConfermeId implements java.io.Serializable {

	private String idSintomo;
	private String NSint;
	private String idPaziente;
	private Date data;
	private String idCartella;

	public ConfermeId() {
	}

	public ConfermeId(String idSintomo, String NSint, String idPaziente,
			Date data, String idCartella) {
		this.idSintomo = idSintomo;
		this.NSint = NSint;
		this.idPaziente = idPaziente;
		this.data = data;
		this.idCartella = idCartella;
	}

	public String getIdSintomo() {
		return this.idSintomo;
	}

	public void setIdSintomo(String idSintomo) {
		this.idSintomo = idSintomo;
	}

	public String getNSint() {
		return this.NSint;
	}

	public void setNSint(String NSint) {
		this.NSint = NSint;
	}

	public String getIdPaziente() {
		return this.idPaziente;
	}

	public void setIdPaziente(String idPaziente) {
		this.idPaziente = idPaziente;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public String getIdCartella() {
		return this.idCartella;
	}

	public void setIdCartella(String idCartella) {
		this.idCartella = idCartella;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConfermeId))
			return false;
		ConfermeId castOther = (ConfermeId) other;

		return ((this.getIdSintomo() == castOther.getIdSintomo()) || (this
				.getIdSintomo() != null && castOther.getIdSintomo() != null && this
				.getIdSintomo().equals(castOther.getIdSintomo())))
				&& ((this.getNSint() == castOther.getNSint()) || (this
						.getNSint() != null && castOther.getNSint() != null && this
						.getNSint().equals(castOther.getNSint())))
				&& ((this.getIdPaziente() == castOther.getIdPaziente()) || (this
						.getIdPaziente() != null
						&& castOther.getIdPaziente() != null && this
						.getIdPaziente().equals(castOther.getIdPaziente())))
				&& ((this.getData() == castOther.getData()) || (this.getData() != null
						&& castOther.getData() != null && this.getData()
						.equals(castOther.getData())))
				&& ((this.getIdCartella() == castOther.getIdCartella()) || (this
						.getIdCartella() != null
						&& castOther.getIdCartella() != null && this
						.getIdCartella().equals(castOther.getIdCartella())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdSintomo() == null ? 0 : this.getIdSintomo().hashCode());
		result = 37 * result
				+ (getNSint() == null ? 0 : this.getNSint().hashCode());
		result = 37
				* result
				+ (getIdPaziente() == null ? 0 : this.getIdPaziente()
						.hashCode());
		result = 37 * result
				+ (getData() == null ? 0 : this.getData().hashCode());
		result = 37
				* result
				+ (getIdCartella() == null ? 0 : this.getIdCartella()
						.hashCode());
		return result;
	}

}
