package bean;

// Generated 12-lug-2014 19.15.43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medico generated by hbm2java
 */
public class Medico implements java.io.Serializable {

	private String id;
	private String nome;
	private String cognome;
	private String primario;
	private String psw;
	private Date inizioAttivita;
	private Set diagnosis = new HashSet(0);
	private Set specDelMedicos = new HashSet(0);

	public Medico() {
	}

	public Medico(String id, String nome, String cognome, String primario,
			String psw, Date inizioAttivita) {
		this.id = id;
		this.nome = nome;
		this.cognome = cognome;
		this.primario = primario;
		this.psw = psw;
		this.inizioAttivita = inizioAttivita;
	}

	public Medico(String id, String nome, String cognome, String primario,
			String psw, Date inizioAttivita, Set diagnosis, Set specDelMedicos) {
		this.id = id;
		this.nome = nome;
		this.cognome = cognome;
		this.primario = primario;
		this.psw = psw;
		this.inizioAttivita = inizioAttivita;
		this.diagnosis = diagnosis;
		this.specDelMedicos = specDelMedicos;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public String getPrimario() {
		return this.primario;
	}

	public void setPrimario(String primario) {
		this.primario = primario;
	}

	public String getPsw() {
		return this.psw;
	}

	public void setPsw(String psw) {
		this.psw = psw;
	}

	public Date getInizioAttivita() {
		return this.inizioAttivita;
	}

	public void setInizioAttivita(Date inizioAttivita) {
		this.inizioAttivita = inizioAttivita;
	}

	public Set getDiagnosis() {
		return this.diagnosis;
	}

	public void setDiagnosis(Set diagnosis) {
		this.diagnosis = diagnosis;
	}

	public Set getSpecDelMedicos() {
		return this.specDelMedicos;
	}

	public void setSpecDelMedicos(Set specDelMedicos) {
		this.specDelMedicos = specDelMedicos;
	}

}
