package bean;

// Generated 12-lug-2014 19.15.43 by Hibernate Tools 3.4.0.CR1

/**
 * RischiPaziente generated by hbm2java
 */
public class RischiPaziente implements java.io.Serializable {

	private RischiPazienteId id;
	private FattoriRischio fattoriRischio;
	private Paziente paziente;

	public RischiPaziente() {
	}

	public RischiPaziente(RischiPazienteId id, FattoriRischio fattoriRischio,
			Paziente paziente) {
		this.id = id;
		this.fattoriRischio = fattoriRischio;
		this.paziente = paziente;
	}

	public RischiPazienteId getId() {
		return this.id;
	}

	public void setId(RischiPazienteId id) {
		this.id = id;
	}

	public FattoriRischio getFattoriRischio() {
		return this.fattoriRischio;
	}

	public void setFattoriRischio(FattoriRischio fattoriRischio) {
		this.fattoriRischio = fattoriRischio;
	}

	public Paziente getPaziente() {
		return this.paziente;
	}

	public void setPaziente(Paziente paziente) {
		this.paziente = paziente;
	}

}
