package bean;

// Generated 12-lug-2014 19.15.43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Specializzazioni generated by hbm2java
 */
public class Specializzazioni implements java.io.Serializable {

	private String nome;
	private Set specDelMedicos = new HashSet(0);

	public Specializzazioni() {
	}

	public Specializzazioni(String nome) {
		this.nome = nome;
	}

	public Specializzazioni(String nome, Set specDelMedicos) {
		this.nome = nome;
		this.specDelMedicos = specDelMedicos;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set getSpecDelMedicos() {
		return this.specDelMedicos;
	}

	public void setSpecDelMedicos(Set specDelMedicos) {
		this.specDelMedicos = specDelMedicos;
	}

}
