package bean;

// Generated 12-lug-2014 19.15.43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TerapieId generated by hbm2java
 */
public class TerapieId implements java.io.Serializable {

	private String idCartella;
	private Date inizio;
	private Date fine;
	private int frequenza;
	private float dose;
	private String farmaco;

	public TerapieId() {
	}

	public TerapieId(String idCartella, Date inizio, Date fine, int frequenza,
			float dose, String farmaco) {
		this.idCartella = idCartella;
		this.inizio = inizio;
		this.fine = fine;
		this.frequenza = frequenza;
		this.dose = dose;
		this.farmaco = farmaco;
	}

	public String getIdCartella() {
		return this.idCartella;
	}

	public void setIdCartella(String idCartella) {
		this.idCartella = idCartella;
	}

	public Date getInizio() {
		return this.inizio;
	}

	public void setInizio(Date inizio) {
		this.inizio = inizio;
	}

	public Date getFine() {
		return this.fine;
	}

	public void setFine(Date fine) {
		this.fine = fine;
	}

	public int getFrequenza() {
		return this.frequenza;
	}

	public void setFrequenza(int frequenza) {
		this.frequenza = frequenza;
	}

	public float getDose() {
		return this.dose;
	}

	public void setDose(float dose) {
		this.dose = dose;
	}

	public String getFarmaco() {
		return this.farmaco;
	}

	public void setFarmaco(String farmaco) {
		this.farmaco = farmaco;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TerapieId))
			return false;
		TerapieId castOther = (TerapieId) other;

		return ((this.getIdCartella() == castOther.getIdCartella()) || (this
				.getIdCartella() != null && castOther.getIdCartella() != null && this
				.getIdCartella().equals(castOther.getIdCartella())))
				&& ((this.getInizio() == castOther.getInizio()) || (this
						.getInizio() != null && castOther.getInizio() != null && this
						.getInizio().equals(castOther.getInizio())))
				&& ((this.getFine() == castOther.getFine()) || (this.getFine() != null
						&& castOther.getFine() != null && this.getFine()
						.equals(castOther.getFine())))
				&& (this.getFrequenza() == castOther.getFrequenza())
				&& (this.getDose() == castOther.getDose())
				&& ((this.getFarmaco() == castOther.getFarmaco()) || (this
						.getFarmaco() != null && castOther.getFarmaco() != null && this
						.getFarmaco().equals(castOther.getFarmaco())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdCartella() == null ? 0 : this.getIdCartella()
						.hashCode());
		result = 37 * result
				+ (getInizio() == null ? 0 : this.getInizio().hashCode());
		result = 37 * result
				+ (getFine() == null ? 0 : this.getFine().hashCode());
		result = 37 * result + this.getFrequenza();
		result = 37 * result + (int) this.getDose();
		result = 37 * result
				+ (getFarmaco() == null ? 0 : this.getFarmaco().hashCode());
		return result;
	}

}
