package bean;

// Generated 9-lug-2014 12.20.42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Sintomi generated by hbm2java
 */
public class Sintomi implements java.io.Serializable {

	private SintomiId id;
	private Paziente paziente;
	private String intensita;
	private Set contraddizionis = new HashSet(0);
	private Set confermes = new HashSet(0);

	public Sintomi() {
	}

	public Sintomi(SintomiId id, Paziente paziente, String intensita) {
		this.id = id;
		this.paziente = paziente;
		this.intensita = intensita;
	}

	public Sintomi(SintomiId id, Paziente paziente, String intensita,
			Set contraddizionis, Set confermes) {
		this.id = id;
		this.paziente = paziente;
		this.intensita = intensita;
		this.contraddizionis = contraddizionis;
		this.confermes = confermes;
	}

	public SintomiId getId() {
		return this.id;
	}

	public void setId(SintomiId id) {
		this.id = id;
	}

	public Paziente getPaziente() {
		return this.paziente;
	}

	public void setPaziente(Paziente paziente) {
		this.paziente = paziente;
	}

	public String getIntensita() {
		return this.intensita;
	}

	public void setIntensita(String intensita) {
		this.intensita = intensita;
	}

	public Set getContraddizionis() {
		return this.contraddizionis;
	}

	public void setContraddizionis(Set contraddizionis) {
		this.contraddizionis = contraddizionis;
	}

	public Set getConfermes() {
		return this.confermes;
	}

	public void setConfermes(Set confermes) {
		this.confermes = confermes;
	}

}
