package bean;

// Generated 9-lug-2014 12.20.42 by Hibernate Tools 3.4.0.CR1

/**
 * Conferme generated by hbm2java
 */
public class Conferme implements java.io.Serializable {

	private ConfermeId id;
	private Sintomi sintomi;
	private Diagnosi diagnosi;

	public Conferme() {
	}

	public Conferme(ConfermeId id, Sintomi sintomi, Diagnosi diagnosi) {
		this.id = id;
		this.sintomi = sintomi;
		this.diagnosi = diagnosi;
	}

	public ConfermeId getId() {
		return this.id;
	}

	public void setId(ConfermeId id) {
		this.id = id;
	}

	public Sintomi getSintomi() {
		return this.sintomi;
	}

	public void setSintomi(Sintomi sintomi) {
		this.sintomi = sintomi;
	}

	public Diagnosi getDiagnosi() {
		return this.diagnosi;
	}

	public void setDiagnosi(Diagnosi diagnosi) {
		this.diagnosi = diagnosi;
	}

}
